name: Check Version Updated

on:
  pull_request:
    branches: [master]

jobs:
  pkg-size-report:
    name: Check Version Updated
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Cancel old runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: Check version updated
        shell: bash
        run: ./.github/scripts/check_version_updated.sh
