name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          package_version=$(jq -r .version package.json)
          echo "version=${package_version}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
