name: Vitest

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Cancel old runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '16.x'

      - name: Install packages
        # We ignore engines here to avoid issues
        # installing dependencies that are not needed
        # for the build or to run these tests.
        run: yarn --ignore-engines

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test --silent
